### PR TITLE
s/ can be done simple / can be done simply /

### PR DESCRIPTION
**Pull request by 1nickt**

### CODE REVIEW

**Comment by timbunce** [comment]
Thanks Nick!

**Comment by 1nickt** [comment]
You're welcome. Nice to see you ;-)

**Comment by timbunce** [comment]
And you. I hope you're keeping well. Glad to see you're still using perl, at least a little. :)

**Comment by 1nickt** [comment]
Tim,

I am doing OK. My younger son who wasn't even born when we were VClicking
is now 13 and a half, has been over to see Granny and Granddad at
Cooksbridge by himself last summer ... how time flies!

Are you still living in western Eire? I was always jealous of that set up.
My fiancee is all for dropping out to the remotest countryside somewhere to
grow veggies and deliver babies (she's a nurse) ... sounds great to me.

Maybe that is partially why I am rebirthing myself as a Perl developer. The
ability to work remotely and still earn enough to support a couple of
people living a simple hippie life in the country ... and have fun doing
it!

I did take several years away from Perl (some regrets about that, but some
experiences I wouldn't have had otherwise),  after keeping myself going
with some webapps for a few years after VCLK. Raising the boy, etc. Have
recently jumped back into things, and was pleasantly surprised to find that
my Perl skills are not obsolete as I feared they might be, and in fact I
still have pretty decent chops.

Most "programmers" still can't program, it seems. And the stuff that is now
the subject of acronyms and college courses and managerial bloviation, such
as "Agile" and "Modern Perl" etc., which intimidated me at first when I
began to think I'd like to get back into it, turns out to be the same stuff
we were doing and practicing at the turn of the millennium! I guess we were
just quite far ahead of the pack.

So I am pleasantly encouraged and hoping that I'll be able to find a nice
set up working quietly on elegant, useful code, while not having to deal
too much with the rest of the world! Have been trying to participate where
possible, on PerlMonks, CPAN and elsewhere, and am loving github, which
allows you to contribute, even if it's just a docutypo, almost without
stopping what you were doing!

It was great to find that you are well and still the main maintainer of the
DBI. I am very happy for you.

Hope we'll see a little more of each other, at least on the internets, and
who knows, maybe back in the UK/Ireland one of these days. My fiancee
Meaghan is an Irish redhead -- from Texas. Dangerous!

Very best wishes,

Nick

**Comment by ribasushi** [comment]
Hi @1nickt !

I figured it's a good idea to remind you that this is a public bugtracker. I am going out on a limb, but I think you probably wanted to keep this exchange private :)

Cheers!

**Comment by 1nickt** [comment]
Thanks man. Just replying to Tim!

**Pull request merged**
