### PR TITLE
Fix DBI documentation about eval { } usage

### PR DESCRIPTION
**Pull request by pali**
Explanation at: https://metacpan.org/pod/Try::Tiny#might-not-be-a-true-value

### CODE REVIEW

**Comment by pali** [comment]
Hi! Can somebody review & merge this patch?

**Comment by charsbar** [comment]
This patch doesn't address all the ```$@``` usage in the pod. At least ```if ($@) { ... }``` in the body of "RaiseError" section should be modified as well, and it's probably better to fix two ```$@```s after ```eval``` block in the example in "Timeout" section accordingly. Also in the context of this patch, ```$@``` may be undef and thus lead to warnings if stringified unconditionally (which is not a problem of the current doc because ```$@``` itself is tested beforehand). Declaring the same ```my $failed;``` twice (in 7533 and 7535) seems a bit awkward to me as well.

But, do we really need this kind of correctness here, especially when we don't do this in the actual DBI code (yet)?

**Comment by pali** [comment]
You are right documentation around RaiseError and Timeout needs to be updated too. Now it is fixed.

Normally after `eval { }` which do not fail is `$@` set to `''` empty string which do not throw warning. But yes in some cases (maybe object destructor at the end of eval block which?) manual assignment of undef to `$@` could cause such problem. But I guess manual assignment of undef is not good practice and warning here could help user to debug "buggy" code.

Anyway, I added check for `defined` at places where is used string `eq` comparison.

And question if we need to be correct here... Yes, documentation must be always correct! (if it is incorrect it should be fixed) To inform users how to correctly use library code. Documentation is the first (and probably also last) thing which user read before using code

**Comment by charsbar** [comment]
If this level of correctness really matters here, why not just use more correct Try::Tiny to hide the gory details not to surprise readers (eg. what's this sudden ```1;``` for...), though using Try::Tiny itself may require extra explanation (why Try::Tiny and why $_ -- it's explained in the Try::Tiny doc, but kinda surprising at first sight)?

IMHO the original is good enough without adding extra complexity.

**Comment by pali** [comment]
Try::Tiny is big and IIRC some DBIx module stopped using it because of very big overhead...

And moreover original usage of eval is incorrect, that `1;` is crucial in eval usage and shuld be used.

I still think that documentation must be correct. Code examples are what people copy+paste in their code. And to prevent other people to spend their time in debugging, rather write *correct* code in examples instead of some not-fully-correct (=incorrect).

**Comment by pali** [comment]
@charsbar PING. Do you really dislike my change for having correct examples in documentations?

**Comment by charsbar** [comment]
@pali, as I said above, if that level of correctness really matters to you, why not just use Try::Tiny, or maybe Try::Catch if you worry about the overhead of Try::Tiny. Your "correctness" covers only half of the problems of eval (you forgot to preserve the previous $@, and if you think $@ check is "incorrect", you probably shouldn't depend on the content of $@ at all as it may be clobbered). It's ugly to write that boilerplate repeatedly, and also adds more complexity than necessary in many cases. See also perlfunc (for eval, alarm, die etc). If you want to do more than what's described there, it's probably better to add some explanation not to surprise people, and I'd rather suggest to use Try::Tiny to avoid that explanation. However, as I said above, I'd prefer to keep the original because it usually just works unless you do something too clever.

Anyway, that's just my opinion. Let's wait until someone chimes in.

**Comment by timbunce** [comment]
Thanks @pali.
I'm inclined to go with the PR, based on a quick skim.
I'll wait till I get around to viewing it locally before applying.

**Comment by timbunce** [comment]
In the end I agreed with both of you to some extent in 93faa5d :)
I've used `Try::Tiny` to keep the simple examples both simple and correct.
I've also simplified some old wording.
I've kept the more complex SIGALRM examples the way @pali wrote them since they're not simple to start with :)

@pali, I fumbled the way I merged this so you didn't get a credit in the commit message. You will in the Changes though. Thanks!

**Comment by pali** [comment]
Ok, but in your commit is syntax error, you forgot semicolon.

**Pull request closed without merging**
