### PR TITLE
Correct Isues generated by #21

### PR DESCRIPTION
**Pull request by jluis**
I copied the LICENSE File from a previous CPAN pull request chalenge And missed changin some of the previous author referneces inside the file

### CODE REVIEW

**Comment by jluis** [comment]
In my defense  the error was in the first verision too :)

**Comment by jluis** [comment]
In my defensense the error was inb the first version too and in spanish we don't have the 'E' for Irlanda :)

**Comment by karenetheridge** [comment]
cpanm App::Software::License
    software-license --holder 'Tim Bunce' --license Perl_5 --type fulltext --year 1992 > LICENSE

**Comment by jluis** [comment]
@karenetheridge thanks I didn't know that application

**Pull request closed without merging**
